# Generated by Django 4.0.4 on 2022-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('courseName', models.CharField(max_length=50)),
                ('numberOfHours', models.IntegerField()),
                ('lectureDay', models.CharField(max_length=50)),
                ('hallNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ID', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('university', models.CharField(max_length=50)),
                ('gendar', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
