# Generated by Django 4.0.4 on 2022-05-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_id_course_courseid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gendar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentDepartment',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
    ]
