# Generated by Django 4.0.4 on 2022-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_course_remove_student_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(default='cairo', max_length=50),
            preserve_default=False,
        ),
    ]
