# Generated by Django 4.0.4 on 2022-05-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_student_dateofbirth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gendar',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
