# Generated by Django 4.0.4 on 2022-05-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_gendar_student_gender_student_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
