# Generated by Django 4.0.4 on 2022-05-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_student_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateTimeField(default='2001-06-15'),
        ),
    ]
