# Generated by Django 4.0.4 on 2022-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_student_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='course2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='course3',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
